# Generated by Django 3.2.16 on 2023-07-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_alter_follow_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
